[workspace]
members = ["model", "server", "tools", "policy-engine"]

[workspace.dependencies]
tokio = ">=1.25.0"
futures = "0.3.26"
pin-project = "1.0.12"
http = ">=0.2.9"
axum = ">=0.6.7"
jsonwebtoken = ">=8.2.0"
serde = ">=1.0.152"
serde_json = ">=1.0.91"
serde_urlencoded = ">=0.7.1"
tracing = ">=0.1.37"
tracing-subscriber = ">=0.3.16"
tracing-log = ">=0.1.3"
tracing-error = ">=0.2.0"
tower = "0.4.13"
tower-http = ">=0.3.5"
tower-cookies = ">=0.9.0"
refinery = ">=0.8.7"
deadpool-postgres = ">=0.10.5"
tokio-postgres =">=0.7.7"
sqlx = { version = ">=0.6.2", features = ["runtime-tokio-rustls"] }
opentelemetry-jaeger = ">=0.17.0"
opentelemetry = ">=0.18.0"
tracing-opentelemetry = ">=0.18.0"
metrics = ">=0.20.1"
metrics-exporter-prometheus = ">=0.11.0"
config = { version = ">=0.13.3", default-features = false }
rhai = ">=1.12.0"
argon2 = ">=0.4.1"
moka = ">=0.10.0"
base64 = ">=0.21.0"
once_cell = ">=1.17.1"
rand = ">=0.8.5"
uuid = ">=1.3.0"
time = ">=0.3.19"
impl-tools = ">=0.8.0"
parking_lot = { version = ">=0.12.1", features = ["send_guard"] }
futures-util = ">=0.3.26"
async-trait = ">=0.1.64"
schemars = ">=0.8.11"
derive_more = { git = "https://github.com/JelteF/derive_more" }