[workspace]
members = ["shared", "server", "outpost"]

[workspace.dependencies]
axum = ">=0.6.4"
serde = ">=1.0.152"
serde_json = ">=1.0.91"
config = { version = ">=0.13.3", default-features = false }
tracing = ">=0.1.37"
tokio = ">=1.24.2"
tracing-subscriber = ">=0.3.16"
once_cell = ">=1.17.0"
sqlx = ">=0.6.2"
