[workspace]
members = ["model", "server"]

[workspace.dependencies]
axum = ">=0.6.4"
serde = ">=1.0.152"
serde_json = ">=1.0.91"
config = { version = ">=0.13.3", default-features = false }
tracing = ">=0.1.37"
tokio = ">=1.24.2"
tracing-subscriber = ">=0.3.16"
once_cell = ">=1.17.0"
sqlx = { version = ">=0.6.2", features = ["runtime-tokio-rustls"] }
uuid = ">=1.2.2"
time = { version = "0.3.17" }
impl-tools = ">=0.8.0"
async-trait = ">=0.1.63"
axum-core = ">=0.3.2"
schemars = "0.8.11"
derive_more = { git = "https://github.com/JelteF/derive_more" }
typeshare = "1.0.0"