version: "3.9"
services:
  authentra:
    build: .
    environment:
      AUTHUST_POSTGRES__HOST: db
      AUTHUST_POSTGRES__DATABASE: authentra
      AUTHUST_POSTGRES__USER: authentra
      AUTHUST_POSTGRES__PASSWORD: authentra
      AUTHUST_SECRET: really_secret
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: authentra
      POSTGRES_PASSWORD: authentra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: true
    healthcheck:
      test: curl --fail http://jaeger:16686/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
