apiVersion: v1
kind: Secret
metadata:
  name: authust
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  secret: {{ randAlphaNum 68 | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}
  postgres-password: {{ randAlphaNum 32 | b64enc}}