[package]
name = "authust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# This feature only has an effect when debug_assertions are turned on
dev-mode = []

[dependencies]
serde = { workspace = true, features = ["derive"] }
config = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
once_cell = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
sqlx = { workspace = true, features = [
  "runtime-tokio-rustls",
  "postgres",
  "uuid",
  "time",
  "offline",
] }
http.workspace = true
uuid = { workspace = true, features = ["serde"] }
time = { workspace = true, features = ["serde"] }
parking_lot.workspace = true
jsonwebtoken = "8.2.0"
rand = "0.8.5"
futures-util = "0.3.25"
# Wait for tower-cookies to update to new version
async-trait = { workspace = true }
argon2 = "0.4.1"
derive_more = { workspace = true, features = [
  "error",
  "display",
  "from",
] }
tracing-error = "0.2.0"
moka = "0.9.6"
handlebars = "4.3.6"
impl-tools = "0.6.2"
serde_json = { workspace = true, features = ["preserve_order"] }
axum = { workspace = true, features = ["headers", "macros"] }
axum-extra = { version = "0.4.2", features = [] }
tower = "0.4.13"
futures = "0.3.26"
pin-project-lite = "0.2.9"
pin-project = "1.0.12"
tower-http = { version = "0.3.5", features = ["trace", "cors", "fs"] }
serde_urlencoded = "0.7.1"
# cookie = { version = "0.17.0", features = ["percent-encoding"] }
tower-cookies = { git = "https://github.com/DSeeLP/tower-cookies" }
# parking_lot = { workspace = true }
model = { path = "../model", features = ["axum", "sqlx"], package = "authust_model" }
opentelemetry-jaeger = "0.17.0"
opentelemetry = { version = "0.18.0", features = ["trace"] }
tracing-opentelemetry = "0.18.0"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
policy-engine = { version = "0.1.0", path = "../policy-engine" }
